const environment = process.env.NODE_ENV
const isDevelopment = 'development' === environment

module.exports = ({options}) => ({

  plugins: {
    stylelint: {
      /**
       *	https://stylelint.io/user-guide/rules/
       */
      "rules": {
        "at-rule-blacklist": [],
        "at-rule-name-case": "lower",
        "at-rule-name-newline-after": "always-multi-line",
        "at-rule-no-unknown": true,
        "at-rule-no-vendor-prefix": true,
        "at-rule-semicolon-newline-after": "always",
        "block-closing-brace-empty-line-before": "never",
        "block-no-empty": true,
        "color-hex-case": "lower",
        "color-hex-length": "short",
        "color-named": "never",
        "color-no-invalid-hex": true,
        "comment-whitespace-inside": "always",
        "comment-word-blacklist": [],
        "custom-property-empty-line-before": "never",
        "declaration-block-no-shorthand-property-overrides": true,
        "declaration-colon-newline-after": "always-multi-line",
        "declaration-empty-line-before": "never",
        "font-family-no-missing-generic-family-keyword": true,
        "function-calc-no-unspaced-operator": true,
        "function-linear-gradient-no-nonstandard-direction": true,
        "function-max-empty-lines": 0,
        "function-name-case": "lower",
        "function-parentheses-newline-inside": "never-multi-line",
        "function-parentheses-space-inside": "never",
        "function-url-quotes": "never",
        "media-feature-name-case": "lower",
        "media-feature-name-no-unknown": true,
        "media-feature-name-no-vendor-prefix": true,
        "media-feature-parentheses-space-inside": "never",
        "no-duplicate-at-import-rules": true,
        "no-empty-source": true,
        "no-extra-semicolons": true,
        "no-invalid-double-slash-comments": true,
        "no-missing-end-of-source-newline": true,
        "number-max-precision": 10,
        "number-no-trailing-zeros": true,
        "property-case": "lower",
        "property-no-unknown": true,
        "selector-attribute-brackets-space-inside": "never",
        "selector-attribute-quotes": "always",
        "selector-descendant-combinator-no-non-space": true,
        "selector-list-comma-newline-before": "never-multi-line",
        "selector-max-empty-lines": 0,
        "selector-no-vendor-prefix": true,
        "selector-pseudo-class-case": "lower",
        "selector-pseudo-class-no-unknown": true,
        "selector-pseudo-class-parentheses-space-inside": "never",
        "selector-pseudo-element-case": "lower",
        "selector-pseudo-element-colon-notation": "single",
        "selector-pseudo-element-no-unknown": true,
        "selector-type-case": "lower",
        "string-no-newline": true,
        "time-min-milliseconds": 0,
        "unit-case": "lower",
        "unit-no-unknown": true,
        "value-keyword-case": "lower",
        "value-list-max-empty-lines": 0,
        "value-no-vendor-prefix": true,
        ...isDevelopment && { "at-rule-name-space-after": "always" },
        ...isDevelopment && { "at-rule-semicolon-space-before": "never" },
        ...isDevelopment && { "block-closing-brace-newline-after": "always" },
        ...isDevelopment && { "block-closing-brace-space-after": "always-single-line" },
        ...isDevelopment && { "block-closing-brace-space-before": "always" },
        ...isDevelopment && { "block-opening-brace-newline-after": "always" },
        ...isDevelopment && { "block-opening-brace-space-after": "always-single-line" },
        ...isDevelopment && { "block-opening-brace-space-before": "always" },
        ...isDevelopment && { "color-hex-length": "long" },
        ...isDevelopment && { "declaration-bang-space-after": "never" },
        ...isDevelopment && { "declaration-bang-space-before": "always" },
        ...isDevelopment && { "declaration-block-semicolon-newline-after": "always" },
        ...isDevelopment && { "declaration-block-single-line-max-declarations": 1 },
        ...isDevelopment && { "declaration-block-trailing-semicolon": "always" },
        ...isDevelopment && { "declaration-colon-space-after": "always" },
        ...isDevelopment && { "declaration-colon-space-before": "never" },
        ...isDevelopment && { "function-comma-space-after": "always" },
        ...isDevelopment && { "function-comma-space-before": "never" },
        ...isDevelopment && { "function-whitespace-after": "always" },
        ...isDevelopment && { "media-feature-colon-space-after": "always" },
        ...isDevelopment && { "media-feature-colon-space-before": "never" },
        ...isDevelopment && { "media-feature-range-operator-space-after": "always" },
        ...isDevelopment && { "media-feature-range-operator-space-before": "always" },
        ...isDevelopment && { "number-leading-zero": "always" },
        ...isDevelopment && { "selector-attribute-operator-space-after": "never" },
        ...isDevelopment && { "selector-attribute-operator-space-before": "never" },
        ...isDevelopment && { "selector-combinator-space-after": "always" },
        ...isDevelopment && { "selector-combinator-space-before": "always" },
        ...isDevelopment && { "selector-list-comma-space-before": "never" },
        ...isDevelopment && { "value-list-comma-newline-after": "always-multi-line" },
        ...isDevelopment && { "value-list-comma-newline-before": "never-multi-line" },
        ...isDevelopment && { "value-list-comma-space-after": "always" },
      }
    },
    autoprefixer: {
      "grid": true,
    },
    /**
     * http://cssnano.co/guides/optimisations/
     */
    cssnano: (
      options.minify === true ?
        {
          "autoprefixer": false,
          "calc": true,
          "colormin": true,
          "cssDeclarationSorter": true,
          "discardComments": true,
          "discardDuplicates": true,
          "discardEmpty": true,
          "discardOverridden": true,
          "mergeLonghand": true,
          "mergeRules": true,
          "minifyGradients": true,
          "minifyParams": true,
          "minifySelectors": true,
          "normalizeCharset": true,
          "normalizeDisplayValues": true,
          "normalizePositions": true,
          "normalizeRepeatStyle": true,
          "normalizeString": true,
          "normalizeUnicode": true,
          "normalizeUrl": true,
          "normalizeWhitespace": true,
          "orderedValues": true,
          "reduceInitial": true,
          "reduceTransforms": true,
          "safe": true,
          "svgo": true,
          "uniqueSelectors": true,
        }
        : false
    )
  }
})